services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:8000
    depends_on:
      - db

  
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432


volumes:
  postgres_data:
